// Supabase configuration
export const SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL || '';
export const SUPABASE_ANON_KEY = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || '';

// App configuration
export const APP_NAME = '3a9ari';
export const CURRENCY = 'دت';
export const AREA_UNIT = 'متر مربع';

// Units Configuration  
export const AREA_UNITS = [
  { id: 'm²', label: 'م²' },
  { id: 'hectare', label: 'هكتار' },
] as const;

export const PRICE_UNITS = [
  { id: 'tnd', label: 'دت' },
  { id: 'tnd/m²', label: 'دت/م²' },
  { id: 'tnd/hectare', label: 'دت/هكتار' },
] as const;

// Helper types for units
export type AreaUnit = typeof AREA_UNITS[number]['id'];
export type PriceUnit = typeof PRICE_UNITS[number]['id'];

// Property Categories
export const PROPERTY_CATEGORIES = [
  { id: 'shop_sale', label: 'محل للبيع' },
  { id: 'shop_rent', label: 'محل للإيجار' },
  { id: 'office_sale', label: 'مكتب للبيع' },
  { id: 'office_rent', label: 'مكتب للإيجار' },
  { id: 'warehouse_sale', label: 'مستودع للبيع' },
  { id: 'warehouse_rent', label: 'مستودع للإيجار' },
  { id: 'commercial_sale', label: 'أصل تجاري للبيع' },
  { id: 'agricultural_land_sale', label: 'أرض فلاحية للبيع' },
  { id: 'agricultural_land_rent', label: 'أرض فلاحية للإيجار' },
  { id: 'residential_land_sale', label: 'أرض سكنية للبيع' },
  { id: 'apartment_sale', label: 'شقة للبيع' },
  { id: 'apartment_rent', label: 'شقة للإيجار' },
  { id: 'villa_sale', label: 'فيلا للبيع' },
  { id: 'villa_rent', label: 'فيلا للإيجار' },
  { id: 'house_sale', label: 'منزل للبيع' },
  { id: 'house_rent', label: 'منزل للإيجار' },
  { id: 'duplex_sale', label: 'دوبلكس للبيع' },
  { id: 'duplex_rent', label: 'دوبلكس للإيجار' },
  { id: 'room_rent', label: 'غرفة للإيجار' },
  { id: 'building_sale', label: 'عمارة للبيع' },
  { id: 'holiday_rental', label: 'إيجار للعطل والسياحة' },
] as const;

// Helper type for property category
export type PropertyCategory = typeof PROPERTY_CATEGORIES[number];

// Locations and Delegations
export interface Delegation {
  id: string;
  label: string;
}

export interface Location {
  id: string;
  label: string;
  delegations: Delegation[];
}

export const LOCATIONS: Location[] = [
  {
    id: 'ariana',
    label: 'أريانة',
    delegations: [
      { id: 'ariana', label: 'أريانة' },
      { id: 'ettadhamen', label: 'التضامن' },
      { id: 'kalaat_el_andalous', label: 'قلعة الأندلس' },
      { id: 'mnihla', label: 'منيهلة' },
      { id: 'raoued', label: 'رواد' },
      { id: 'sidi_thabet', label: 'سيدي ثابت' },
      { id: 'soukra', label: 'سكرة' },
    ],
  },
  {
    id: 'beja',
    label: 'باجة',
    delegations: [
      { id: 'amdoun', label: 'عمدون' },
      { id: 'beja', label: 'باجة' },
      { id: 'goubellat', label: 'قبليط' },
      { id: 'majaz_al_bab', label: 'مجاز الباب' },
      { id: 'nefza', label: 'نفزة' },
      { id: 'teboursouk', label: 'تبرسق' },
      { id: 'testour', label: 'تستور' },
      { id: 'thibar', label: 'تيبار ' },
    ],
  },
  {
    id: 'ben_arous',
    label: 'بن عروس',
    delegations: [
      { id: 'ben_arous', label: 'بن عروس' },
      { id: 'bou_mhel_el_bassatine', label: 'بومهل البساتين' },
      { id: 'el_mourouj', label: 'المرسى' },
      { id: 'ezzahra', label: 'الزهراء' },
      { id: 'fouchana', label: 'فوشانة' },
      { id: 'hammam_chott', label: 'حمام الشط' },
      { id: 'hammam_lif', label: 'حمام الأنف' },
      { id: 'mohamedia', label: 'المحمدية' },
      { id: 'medina_jedida', label: 'المدينة الجديدة' },
      { id: 'megrine', label: 'مقرين' },
      { id: 'mornag', label: 'مرناق' },
      { id: 'rades', label: 'رادس' },
    ],
  },
  {
    id: 'bizerte',
    label: 'بنزرت',
    delegations: [
      { id: 'bizerte', label: 'بنزرت' },
      { id: 'djoumime', label: 'جومين' },
      { id: 'el_alia', label: 'العالية' },
      { id: 'ghar_el_melh', label: 'غار الملح' },
      { id: 'ghezala', label: 'غزالة' },
      { id: 'mateur', label: 'ماطر' },
      { id: 'menzel_bourguiba', label: 'منزل بورقيبة' },
      { id: 'menzel_jemil', label: 'منزل جميل' },
      { id: 'ras_jebel', label: 'رأس الجبل' },
      { id: 'sejenane', label: 'سجنان' },
      { id: 'tinja', label: 'تينجة' },
      { id: 'utica', label: 'أوتيكا'},
      { id: 'zarzouna', label: 'زرزونة' },
    ],
  },
  {
    id: 'gabes',
    label: 'قابس',
    delegations: [
      { id: 'gabes', label: 'قابس' },
      { id: 'ghannouch', label: 'غنوش' },
      { id: 'hamma', label: 'الحامة' },
      { id: 'mareth', label: 'مارث' },
      { id: 'matmata', label: 'مطماطة' },
      { id: 'menzel_habib', label: 'منزل حبيب' },
      { id: 'metouia', label: 'المطوية' },
    ],
  },
  {
    id: 'gafsa',
    label: 'قفصة',
    delegations: [
      { id: 'belkhir', label: 'بلخير' },
      { id: 'gafsa', label: 'قفصة' },
      { id: 'guetar', label: 'قطار' },
      { id: 'ksar', label: 'القصر' },
      { id: 'mdhila', label: 'المظيلة' },
      { id: 'metlaoui', label: 'متلوي' },
      { id: 'oum_larais', label: 'أم العرائس' },
      { id: 'redeyef', label: 'الرديف' },
      { id: 'sened', label: 'سند' },
      { id: 'sidi_aich', label: 'سيدي عيش' },
    ],
  },
  {
    id: 'jendouba',
    label: 'جندوبة',
    delegations: [
      { id: 'ain_draham', label: 'عين دراهم' },
      { id: 'bilta', label: 'بلطة' },
      { id: 'bou_salem', label: 'بوسالم' },
      { id: 'fernana', label: 'فرنانة' },
      { id: 'ghardimaou', label: 'غار الدماء' },
      { id: 'jendouba', label: 'جندوبة' },
      { id: 'oued_melliz', label: 'وادي مليز' },
      { id: 'tabarka', label: 'طبرقة' },
    ],
  },
  {
    id: 'kairouan',
    label: 'القيروان',
    delegations: [
      { id: 'alaa', label: 'علاء' },
      { id: 'bouhajla', label: 'بوحجلة' },
      { id: 'chebika', label: 'شبيكة' },
      { id: 'echrarda', label: 'الشراردة' },
      { id: 'haffouz', label: 'حفوز' },
      { id: 'hajeb_el_ayoun', label: 'حاجب العيون' },
      { id: 'kairouan', label: 'القيروان' },
      { id: 'nasrallah', label: 'نصر الله' },
      { id: 'oueslatia', label: 'أوسلاتية' },
      { id: 'sbikha', label: 'سبيخة' },
    ],
  },
  {
    id: 'kasserine',
    label: 'القصرين',
    delegations: [
      { id: 'ayoun', label: 'العيون' },
      { id: 'ezzouhour', label: 'الزهور' },
      { id: 'feriana', label: 'فريانة' },
      { id: 'foussana', label: 'فوسانة' },
      { id: 'hassi_el_ferid', label: 'حاسي الفريد' },
      { id: 'hidra', label: 'الهيضرة' },
      { id: 'jedelienne', label: 'جدليان' },
      { id: 'kasserine', label: 'القصرين' },
      { id: 'magel_bel_abbes', label: 'ماجل بلعباس' },
      { id: 'sbeitla', label: 'سبيطلة' },
      { id: 'sbiba', label: 'سبيبة' },
      { id: 'thala', label: 'تالة' },
    ],
  },
  {
    id: 'kebili',
    label: 'قبلي',
    delegations: [
      { id: 'douz_north', label: 'دوز الشمالية' },
      { id: 'douz_south', label: 'دوز الجنوبية' },
      { id: 'faouar', label: 'فوار' },
      { id: 'kebili_north', label: 'قبلي الشمالية' },
      { id: 'kebili_south', label: 'قبلي الجنوبية' },
      { id: 'souk_el_ahed', label: 'سوق الأحد' },
    ],
  },
  {
    id: 'kef',
    label: 'الكاف',
    delegations: [
      { id: 'dahmani', label: 'الدهماني' },
      { id: 'es_sers', label: 'السرس' },
      { id: 'jerissa', label: 'جريصة' },
      { id: 'kalaa_khasbat', label: 'قلعة خصبة' },
      { id: 'kalaat_senane', label: 'قلعة سنان' },
      { id: 'kef_east', label: 'الكاف الشرقية' },
      { id: 'kef_west', label: 'الكاف الغربية' },
      { id: 'ksour', label: 'القصور' },
      { id: 'nebeur', label: 'نبر' },
      { id: 'sakiet_sidi_youssef', label: 'ساقية سيدي يوسف' },
      { id: 'tajerouine', label: 'تاجروين' },
      { id: 'touiref', label: 'طويرف' },
    ],
  },
  {
    id: 'mahdia',
    label: 'المهدية',
    delegations: [
      { id: 'boumerdes', label: 'بومرداس' },
      { id: 'chebba', label: 'الشابة' },
      { id: 'chorbane', label: 'شربان' },
      { id: 'el_djem', label: 'الجم' },
      { id: 'hbira', label: 'الهبيرة' },
      { id: 'ksour_essef', label: 'قصور الساف' },
      { id: 'mahdia', label: 'المهدية' },
      { id: 'melloulech', label: 'ملولش' },
      { id: 'ouled_chamekh', label: 'أولاد الشامخ' },
      { id: 'sidi_alouane', label: 'سيدي علوان' },
      { id: 'souassi', label: 'السواسي' },
    ],
  },
  {
    id: 'manouba',
    label: 'منوبة',
    delegations: [
      { id: 'borj_el_amri', label: 'برج العامري' },
      { id: 'douar_hicher', label: 'دوار هيشر' },
      { id: 'el_battan', label: 'البطان' },
      { id: 'jedaida', label: 'الجديدة' },
      { id: 'manouba', label: 'منوبة' },
      { id: 'mornaguia', label: 'مرناقية' },
      { id: 'oued_ellil', label: 'وادي الليل' },
      { id: 'tebourba', label: 'طبربة' },
    ],
  },
  {
    id: 'medenine',
    label: 'مدنين',
    delegations: [
      { id: 'ben_gardane', label: 'بن قردان' },
      { id: 'beni_khedache', label: 'بني خداش' },
      { id: 'djerba_ajim', label: 'جربة أجيم' },
      { id: 'djerba_midoun', label: 'جربة ميدون' },
      { id: 'djerba_houmt_souk', label: 'جربة حومة السوق' },
      { id: 'medenine_north', label: 'مدنين الشمالية' },
      { id: 'medenine_south', label: 'مدنين الجنوبية' },
      { id: 'sidi_makhlouf', label: 'سيدي مخلوف' },
      { id: 'zarzis', label: 'جرجيس' },
    ],
  },
  {
    id: 'monastir',
    label: 'المنستير',
    delegations: [
      { id: 'bekalta', label: 'بقالطة' },
      { id: 'bembla', label: 'بمبلة' },
      { id: 'beni_hassen', label: 'بني حسان' },
      { id: 'jammel', label: 'جمال' },
      { id: 'ksar_hellal', label: 'قصر هلال' },
      { id: 'ksibet_el_mediouni', label: 'قصيبة المديوني' },
      { id: 'moknine', label: 'مكنين' },
      { id: 'monastir', label: 'المنستير' },
      { id: 'ouerdanine', label: 'وردانين' },
      { id: 'sahline', label: 'ساحلين' },
      { id: 'sayada_lamta_bou_hjar', label: 'صيادة لمطة بوحجر' },
      { id: 'teboulba', label: 'طبلبة' },
      { id: 'zeramdine', label: 'زرمدين' },
    ],
  },
  {
    id: 'nabeul',
    label: 'نابل',
    delegations: [
      { id: 'beni_khalled', label: 'بني خالد' },
      { id: 'beni_khiar', label: 'بني خيار' },
      { id: 'bou_argoub', label: 'بو عرقوب' },
      { id: 'dar_chaabane_el_fehri', label: 'دار شعبان الفهري' },
      { id: 'el_mida', label: 'الميدة' },
      { id: 'grombalia', label: 'قرمبالية' },
      { id: 'hammam_ghezaz', label: 'حمام الغزاز' },
      { id: 'hammamet', label: 'حمامات' },
      { id: 'haouaria', label: 'الهوارية' },
      { id: 'kelibia', label: 'قليبية' },
      { id: 'korba', label: 'قربة' },
      { id: 'menzel_bouzelfa', label: 'منزل بوزلفة' },
      { id: 'menzel_temime', label: 'منزل تميم' },
      { id: 'nabeul', label: 'نابل' },
      { id: 'soliman', label: 'سليمان' },
      { id: 'takelsa', label: 'تكلصة' },
    ],
  },
  {
    id: 'sfax',
    label: 'صفاقس',
    delegations: [
      { id: 'agareb', label: 'عقارب' },
      { id: 'bir_ali_ben_khelifa', label: 'بئر علي بن خليفة' },
      { id: 'el_amra', label: 'العامرة' },
      { id: 'el_ghraiba', label: 'الغريبة' },
      { id: 'hencha', label: 'الحنشة' },
      { id: 'jebeniana', label: 'جبنيانة' },
      { id: 'kerkennah', label: 'قرقنة' },
      { id: 'mahres', label: 'المحرس' },
      { id: 'menzel_chaker', label: 'منزل شاكر' },
      { id: 'sakiet_eddaier', label: 'ساقية الدائر' },
      { id: 'sakiet_ezzit', label: 'ساقية الزيت' },
      { id: 'sfax_medina', label: 'صفاقس المدينة' },
      { id: 'sfax_west', label: 'صفاقس الغربية' },
      { id: 'sfax_south', label: 'صفاقس الجنوبية' },
      { id: 'skhira', label: 'السخيرة' },
      { id: 'thyna', label: 'طينة' },
    ],
  },
  {
    id: 'sidi_bouzid',
    label: 'سيدي بوزيد',
    delegations: [
      { id: 'bir_el_hfay', label: 'بئر الحفي' },
      { id: 'jelma', label: 'جلما' },
      { id: 'mazzouna', label: 'مزونة' },
      { id: 'meknassi', label: 'المكناسي' },
      { id: 'menzel_bouzaiene', label: 'منزل بوزيان' },
      { id: 'ouled_haffouz', label: 'أولاد حفوز' },
      { id: 'regueb', label: 'الرقاب' },
      { id: 'sabalat_ouled_asker', label: 'سبالة أولاد عسكر' },
      { id: 'sidi_ali_ben_aoun', label: 'سيدي علي بن عون' },
      { id: 'sidi_bouzid_east', label: 'سيدي بوزيد الشرقية' },
      { id: 'sidi_bouzid_west', label: 'سيدي بوزيد الغربية' },
      { id: 'souk_jedid', label: 'السوق الجديد' },
    ],
  },
  {
    id: 'siliana',
    label: 'سليانة',
    delegations: [
      { id: 'bargou', label: 'برقو' },
      { id: 'bouarada', label: 'بوعرادة' },
      { id: 'el_aroussa', label: 'العروسة' },
      { id: 'el_krib', label: 'الكريب' },
      { id: 'gaafour', label: 'قعفور' },
      { id: 'kesra', label: 'كسرى' },
      { id: 'makthar', label: 'مكثر' },
      { id: 'rouhia', label: 'روحية' },
      { id: 'sidi_bourouis', label: 'سيدي بورويس' },
      { id: 'siliana_north', label: 'سليانة الشمالية' },
      { id: 'siliana_south', label: 'سليانة الجنوبية' },
    ],
  },
  {
    id: 'sousse',
    label: 'سوسة',
    delegations: [
      { id: 'akouda', label: 'أكودة' },
      { id: 'bouficha', label: 'بوفيشة' },
      { id: 'enfidha', label: 'نفيضة' },
      { id: 'hammam_sousse', label: 'حمام سوسة' },
      { id: 'hergla', label: 'هرقلة' },
      { id: 'kalaa_kebira', label: 'القلعة الكبرى' },
      { id: 'kalaa_sghira', label: 'القلعة الصغرى' },
      { id: 'kondar', label: 'كندار' },
      { id: 'msaken', label: 'مساكن' },
      { id: 'sidi_bou_ali', label: 'سيدي بو علي' },
      { id: 'sidi_el_heni', label: 'سيدي الهاني' },
      { id: 'sousse_jaouhara', label: 'سوسة جوهرة' },
      { id: 'sousse_medina', label: 'سوسة المدينة' },
      { id: 'sousse_riadh', label: 'سوسة الرياض' },
      { id: 'sousse_sidi_abdelhamid', label: 'سوسة سيدي عبد الحميد' },
      { id: 'zaouiet_ksibet_thrayet', label: 'زاوية قصيبة الثريات' },
    ],
  },
  {
    id: 'tataouine',
    label: 'تطاوين',
    delegations: [
      { id: 'bir_lahmar', label: 'بئر الأحمر' },
      { id: 'dhiba', label: 'ذهيبة' },
      { id: 'ghomrassen', label: 'غمراسن' },
      { id: 'remada', label: 'رمادة' },
      { id: 'samar', label: 'سمار' },
      { id: 'tataouine', label: 'تطاوين' },
    ],
  },
  {
    id: 'tozeur',
    label: 'توزر',
    delegations: [
      { id: 'degueche', label: 'دقاش' },
      { id: 'hazoua', label: 'حزوة' },
      { id: 'nefta', label: 'نفطة' },
      { id: 'tameghza', label: 'تمغزة' },
      { id: 'tozeur', label: 'توزر' },
    ],
  },
  {
    id: 'tunis',
    label: 'تونس',
    delegations: [
      { id: 'bab_bhar', label: 'باب بحر' },
      { id: 'bab_souika', label: 'باب سويقة' },
      { id: 'carthage', label: 'قرطاج' },
      { id: 'el_khadra_city', label: 'مدينة الخضراء' },
      { id: 'djebel_djelloud', label: 'جبل الجلود' },
      { id: 'el_haraïria', label: 'الهريارية' },
      { id: 'el_kabaria', label: 'الكبارية' },
      { id: 'el_menzah', label: 'المنزه' },
      { id: 'el_omrane', label: 'العمران' },
      { id: 'el_omrane_superieur', label: 'العمران الأعلى' },
      { id: 'el_ouardia', label: 'الوردية' },
      { id: 'ettahrir', label: 'التحرير' },
      { id: 'ezzouhour', label: 'الزهور' },
      { id: 'la_goulette', label: 'حلق الوادي' },
      { id: 'la_marsa', label: 'المرسى' },
      { id: 'le_bardo', label: 'باردو' },
      { id: 'le_kram', label: 'الكرم' },
      { id: 'medina', label: 'المدينة' },
      { id: 'sidi_el_bechir', label: 'سيدي البشير' },
      { id: 'sidi_hassine', label: 'سيدي حسين' },
      { id: 'sijoumi', label: 'سجومي' },
    ],
  },
  {
    id: 'zaghouan',
    label: 'زغوان',
    delegations: [
      { id: 'bir_mchergua', label: 'بئر مشارقة' },
      { id: 'fahs', label: 'فاس' },
      { id: 'nadhour', label: 'ناظور' },
      { id: 'saouaf', label: 'صواف' },
      { id: 'zaghouan', label: 'زغوان' },
      { id: 'zriba', label: 'زريبة' },
    ],
  },
];

// Helper type for location
export type LocationType = typeof LOCATIONS[number];        